spring:
    application:
      name: "armanAirlines"
    config:
      activate:
        on-profile: "prod"
    datasource:
      url: "jdbc:mysql://localhost:3306/webtechproject"
      username: "root"
      password: "testPasswort"
